fuse: dev: Add missing freezer header
Now that commit 56ef0ae6c7cc ("Revert "{fuse, sched/wait}: Replicate
pre-TASK_FREEZABLE behavior on downstream"") has been applied, the freezer
header inclusion is also gone. But fuse_wait_event_killable() is used by commit
f5f8189d8c6fe ("fuse: Use freezable wait in request_wait_answer()") which
requires the header. Add the missing header back to fix compilation:

../fs/fuse/dev.c:480:9: error: call to undeclared function 'freezable_schedule'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  480 |                 err = fuse_wait_event_killable(req->waitq,
      |                       ^
../fs/fuse/fuse_i.h:1171:11: note: expanded from macro 'fuse_wait_event_killable'
 1171 |                 __ret = __fuse_wait_event_killable(wq_head, condition);         \
      |                         ^
../fs/fuse/fuse_i.h:1164:8: note: expanded from macro '__fuse_wait_event_killable'
 1164 |                      freezable_schedule())
      |                      ^
../fs/fuse/dev.c:480:9: note: did you mean 'preempt_schedule'?
../fs/fuse/fuse_i.h:1171:11: note: expanded from macro 'fuse_wait_event_killable'
 1171 |                 __ret = __fuse_wait_event_killable(wq_head, condition);         \
      |                         ^
../fs/fuse/fuse_i.h:1164:8: note: expanded from macro '__fuse_wait_event_killable'
 1164 |                      freezable_schedule())
      |                      ^
../arch/arm64/include/asm/preempt.h:83:6: note: 'preempt_schedule' declared here
   83 | void preempt_schedule(void);
      |      ^

Signed-off-by: Tashfin Shakeer Rhythm <tashfinshakeerrhythm@gmail.com>
Signed-off-by: munel <starscroch90@gmail.com>